const supriseMePromps = [
  "Aquarela de uma paisagem de floresta tropical.",
  "Ilustração de arte digital de um horizonte da cidade à noite.",
  "Desenho a lápis de um leão em seu habitat natural.",
  "Fotografia em preto e branco de uma praia deserta.",
  "Retrato em estilo pop art de um papagaio colorido.",
  "Imagem de design gráfico de uma rua da cidade com um ar vintage.",
  "Pintura a óleo realista de um oceano tempestuoso.",
  "Fotografia em estilo minimalista de uma árvore solitária em um campo.",
  "Pintura abstrata de um pôr do sol sobre as montanhas.",
  "Fotografia surrealista de uma pessoa em uma paisagem onírica.",
  "Ilustração em estilo retrô de um disco voador no espaço.",
  "Renderização de arte digital colorida de uma cidade futurista.",
  "Esboço de uma borboleta em uma flor.",
  "Fotografia de clima pesado de uma floresta nebulosa.",
  "Desenho em estilo de desenho animado de um panda em uma floresta de bambu.",
  "Imagem em estilo mosaico de um horizonte da cidade.",
  "Pintura impressionista de um jardim de flores.",
  "Renderização de arte digital de ficção científica de uma nave espacial pousando em um planeta.",
  "Retrato realista de um cavalo.",
  "Fotografia em estilo vintage de uma rua da cidade em preto e branco.",
  "Imagem de design gráfico de uma paisagem geométrica.",
  "Desenho estilizado de um dragão em voo.",
  "Fotografia de um pôr do sol sobre o oceano com efeito de flare de lente.",
  "Retrato em estilo pop art de uma pessoa com um fundo rosa vibrante.",
  "Imagem em estilo minimalista de um cacto no deserto.",
  "Pintura abstrata de um pássaro em voo.",
  "Ilustração de arte digital de um carro futurista.",
  "Fotografia em preto e branco de uma floresta com neblina.",
  "Aquarela de uma vila à beira-mar.",
  "Desenho a lápis de uma cordilheira.",
  "Ilustração em estilo retrô de uma pessoa andando de bicicleta.",
  "Fotografia surrealista de uma pessoa em uma rua da cidade.",
  "Imagem de design gráfico de uma paisagem montanhosa com um esquema de cores ousado.",
  "Pintura impressionista de um pôr do sol sobre um lago.",
  "Retrato realista de um gato.",
  "Fotografia em estilo vintage de uma pessoa caminhando por uma rua da cidade.",
  "Desenho em estilo de desenho animado de uma girafa em uma savana.",
  "Imagem em estilo mosaico de um pôr do sol sobre as montanhas.",
  "Pintura abstrata de uma flor.",
  "Renderização de arte digital de ficção científica de uma cidade futurista.",
  "Retrato realista de um cachorro.",
  "Fotografia em estilo vintage de um horizonte da cidade ao entardecer.",
];

export { supriseMePromps };
