const supriseMeProps = [
"A watercolor painting of a tropical forest landscape.",
"A digital art illustration of a city skyline at night.",
"A pencil drawing of a lion in its natural habitat.",
"A black and white photograph of a deserted beach.",
"A pop art-style portrait of a colorful parrot.",
"A graphic design image of a city street with a vintage vibe.",
"A realistic oil painting of a stormy ocean.",
"A minimalist-style photograph of a lone tree in a field.",
"An abstract painting of a sunset over the mountains.",
"A surrealistic photograph of a person in a dreamlike landscape.",
"A retro-style illustration of a flying saucer in space.",
"A colorful digital art rendering of a futuristic city.",
"A sketch of a butterfly on a flower.",
"A moody photograph of a misty forest.",
"A cartoon-style drawing of a panda in a bamboo forest.",
"A mosaic-style image of a cityscape.",
"An impressionistic painting of a flower garden.",
"A sci-fi digital art rendering of a spaceship landing on a planet.",
"A realistic portrait of a horse.",
"A vintage-style photograph of a city street in black and white.",
"A graphic design image of a geometric landscape.",
"A stylized drawing of a dragon in flight.",
"A photograph of a sunset over the ocean with a lens flare effect.",
"A pop art-style portrait of a person with a bright pink background.",
"A minimalist-style image of a cactus in a desert.",
"An abstract painting of a bird in flight.",
"A digital art illustration of a futuristic car.",
"A black and white photograph of a forest with fog.",
"A watercolor painting of a seaside village.",
"A pencil drawing of a mountain range.",
"A retro-style illustration of a person riding a bicycle.",
"A surrealistic photograph of a person in a city street.",
"A graphic design image of a mountain landscape with a bold color scheme.",
"An impressionistic painting of a sunset over a lake.",
"A realistic portrait of a cat.",
"A vintage-style photograph of a person walking down a city street.",
"A cartoon-style drawing of a giraffe in a savanna.",
"A mosaic-style image of a sunset over the mountains.",
"An abstract painting of a flower.",
"A sci-fi digital art rendering of a futuristic city.",
"A realistic portrait of a dog.",
"A vintage-style photograph of a city skyline at dusk.",
"A graphic design image of an abstract landscape.",
"A stylized drawing of a phoenix.",
"A photograph of a forest with autumn colors.",
"A pop art-style portrait of a person with a speech bubble.",
"A minimalist-style image of a bird in a nest.",
"An abstract painting of a stormy sky.",
"A digital art illustration of a futuristic train.",
"A black and white photograph of a street musician."

];